# These are supported funding model platforms

custom: ['https://amethyst.rs/donate']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
open_collective: amethyst # Replace with a single Open Collective username
